# Generated by Django 5.2.6 on 2025-10-13 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="标题")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("interview", "面试经验"),
                            ("resume", "简历技巧"),
                            ("career", "行业选择"),
                            ("exam", "笔试攻略"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=50, verbose_name="标签"),
                ),
                ("content", models.TextField(verbose_name="内容")),
                ("view_count", models.IntegerField(default=0, verbose_name="浏览量")),
                ("like_count", models.IntegerField(default=0, verbose_name="点赞数")),
                ("star_count", models.IntegerField(default=0, verbose_name="收藏数")),
                (
                    "comment_count",
                    models.IntegerField(default=0, verbose_name="评论数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "文章帖子",
                "verbose_name_plural": "文章帖子",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="articles/attachments/", verbose_name="附件文件"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="article_publish.article",
                        verbose_name="文件所属文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章附件上传",
                "verbose_name_plural": "文章附件上传",
                "ordering": ["-created_at"],
            },
        ),
    ]
