# Generated by Django 5.2.6 on 2026-01-03 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article_publish", "0003_alter_article_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["-created_at"], "verbose_name": "收藏记录"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"], "verbose_name": "文章评论区"},
        ),
        migrations.AlterModelOptions(
            name="follow",
            options={"ordering": ["-created_at"], "verbose_name": "关注记录"},
        ),
        migrations.AlterModelOptions(
            name="like",
            options={"ordering": ["-created_at"], "verbose_name": "点赞记录"},
        ),
    ]
