# Generated by Django 5.2.6 on 2026-01-03 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "article_publish",
            "0004_alter_collection_options_alter_comment_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="article_publish.article",
                verbose_name="收藏的文章",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="收藏用户",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="article_publish.article",
                verbose_name="评论所属文章",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(verbose_name="评论内容"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="like_count",
            field=models.PositiveIntegerField(default=0, verbose_name="评论点赞数"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="评论者",
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="关注时间"),
        ),
        migrations.AlterField(
            model_name="follow",
            name="followed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="被关注用户",
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
                verbose_name="关注用户",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="article_publish.article",
                verbose_name="点赞的文章",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="article_publish.comment",
                verbose_name="点赞的评论",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="点赞时间"),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="点赞用户",
            ),
        ),
    ]
