# Generated by Django 5.2.6 on 2026-01-18 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "article_publish",
            "0005_alter_collection_article_alter_collection_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="article_publish.comment",
                verbose_name="父评论",
            ),
        ),
    ]
