# Generated by Django 5.2.6 on 2026-01-23 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_publish", "0006_comment_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="follow",
            name="follow_type",
            field=models.CharField(
                choices=[("user", "关注用户"), ("enterprise", "关注企业")],
                default="user",
                max_length=20,
                verbose_name="关注类型",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower", "followed", "follow_type")},
        ),
    ]
