# Generated by Django 5.2.6 on 2026-03-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "article_publish",
            "0007_alter_follow_unique_together_follow_follow_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="公告标题")),
                ("content", models.TextField(verbose_name="公告内容")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, verbose_name="优先级（数字越大越靠前）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统公告",
                "verbose_name_plural": "系统公告",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
