# Generated by Django 5.2.6 on 2026-03-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article_publish", "0008_announcement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Announcement",
        ),
    ]
