# Generated by Django 5.2.6 on 2026-03-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_publish", "0010_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_draft",
            field=models.BooleanField(default=False, verbose_name="是否为草稿"),
        ),
    ]
