# Generated by Django 6.0.2 on 2026-03-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article_publish", "0011_article_is_draft"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "平台社区文章",
                "verbose_name_plural": "平台社区文章",
            },
        ),
    ]
