# Generated by Django 6.0.2 on 2026-03-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article_publish", "0012_alter_article_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "文章帖子",
                "verbose_name_plural": "文章帖子",
            },
        ),
    ]
