# Generated by Django 6.0.2 on 2026-03-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article_publish", "0013_alter_article_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Report",
        ),
    ]
