# Generated by Django 5.2.6 on 2026-01-13 14:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chatroom",
            unique_together={("enterprise_user", "job_seeker_user")},
        ),
    ]
