# Generated by Django 5.2.6 on 2026-01-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_chatroom_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "文本"),
                    ("file", "文件"),
                    ("image", "图片"),
                    ("system", "系统消息"),
                ],
                default="text",
                max_length=20,
                verbose_name="消息类型",
            ),
        ),
    ]
