# Generated by Django 5.2.6 on 2025-10-26 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="企业名称")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="enterprise/logos/",
                        verbose_name="企业Logo",
                    ),
                ),
                ("description", models.TextField(verbose_name="企业简介")),
                (
                    "contact_person",
                    models.CharField(max_length=50, verbose_name="联系人"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="联系电话"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="联系邮箱"),
                ),
                ("address", models.CharField(max_length=500, verbose_name="企业地址")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprise_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "企业信息",
                "verbose_name_plural": "企业信息",
            },
        ),
        migrations.CreateModel(
            name="Recruitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="招聘标题")),
                ("job", models.CharField(max_length=100, verbose_name="职位名称")),
                (
                    "work_location",
                    models.CharField(max_length=200, verbose_name="工作地点"),
                ),
                ("salary", models.CharField(max_length=100, verbose_name="薪资范围")),
                (
                    "experience",
                    models.CharField(max_length=100, verbose_name="工作经验要求"),
                ),
                ("education", models.CharField(max_length=50, verbose_name="学历要求")),
                ("job_desc", models.TextField(verbose_name="职位描述")),
                ("job_require", models.TextField(verbose_name="任职要求")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="是否发布"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitments",
                        to="enterprise.enterprise",
                        verbose_name="所属企业",
                    ),
                ),
            ],
            options={
                "verbose_name": "招聘信息",
                "verbose_name_plural": "招聘信息",
                "ordering": ["-created_at"],
            },
        ),
    ]
