# Generated by Django 5.2.6 on 2025-12-01 10:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enterprise",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "企业信息",
                "verbose_name_plural": "企业信息",
            },
        ),
        migrations.RemoveField(
            model_name="recruitment",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="recruitment",
            name="job",
        ),
        migrations.AddField(
            model_name="enterprise",
            name="industry",
            field=models.CharField(
                choices=[
                    ("IT", "信息技术"),
                    ("FINANCE", "金融"),
                    ("EDUCATION", "教育"),
                    ("MEDIA", "传媒"),
                    ("MANUFACTURING", "制造业"),
                    ("SERVICE", "服务业"),
                    ("OTHER", "其他"),
                ],
                default="OTHER",
                help_text="选择企业主要经营领域",
                max_length=20,
                verbose_name="所属行业",
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="标记企业是否通过平台认证",
                verbose_name="是否认证",
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="scale",
            field=models.CharField(
                choices=[
                    ("MICRO", "微型企业（<10人）"),
                    ("SMALL", "小型企业（10-99人）"),
                    ("MEDIUM", "中型企业（100-999人）"),
                    ("LARGE", "大型企业（1000人以上）"),
                ],
                default="SMALL",
                help_text="选择企业人员规模",
                max_length=20,
                verbose_name="企业规模",
            ),
        ),
        migrations.AddField(
            model_name="recruitment",
            name="deadline",
            field=models.DateField(
                default=datetime.date(2025, 12, 31),
                help_text="招聘信息有效期截止日期",
                verbose_name="截止日期",
            ),
        ),
        migrations.AddField(
            model_name="recruitment",
            name="is_urgent",
            field=models.BooleanField(
                default=False,
                help_text="标记为急聘的职位将获得更多曝光",
                verbose_name="是否急聘",
            ),
        ),
        migrations.AddField(
            model_name="recruitment",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "全职"),
                    ("PART_TIME", "兼职"),
                    ("INTERNSHIP", "实习"),
                ],
                default="全职",
                help_text="选择全职/兼职/实习",
                max_length=20,
                verbose_name="工作类型",
            ),
        ),
        migrations.AddField(
            model_name="recruitment",
            name="number_of_recruits",
            field=models.PositiveIntegerField(
                default=1,
                help_text="填写招聘人数，至少1人",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="招聘人数",
            ),
        ),
        migrations.AddField(
            model_name="recruitment",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "草稿"),
                    ("PUBLISHED", "已发布"),
                    ("EXPIRED", "已过期"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
                verbose_name="招聘状态",
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="address",
            field=models.CharField(
                help_text="请填写详细办公地址", max_length=500, verbose_name="企业地址"
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="contact_email",
            field=models.EmailField(
                help_text="请填写企业官方招聘邮箱",
                max_length=254,
                verbose_name="联系邮箱",
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="contact_person",
            field=models.CharField(
                help_text="请填写负责招聘的联系人姓名",
                max_length=50,
                verbose_name="联系人",
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="contact_phone",
            field=models.CharField(
                help_text="请填写有效的手机号码",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^1[3-9]\\d{9}$", "请输入有效的手机号码"
                    )
                ],
                verbose_name="联系电话",
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="description",
            field=models.TextField(
                help_text="请简要介绍企业主营业务、发展历程等", verbose_name="企业简介"
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="请填写企业全称",
                max_length=200,
                unique=True,
                verbose_name="企业名称",
            ),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="education",
            field=models.CharField(
                choices=[
                    ("HIGH_SCHOOL", "高中及以下"),
                    ("ASSOCIATE", "专科"),
                    ("BACHELOR", "本科"),
                    ("MASTER", "硕士"),
                    ("DOCTOR", "博士及以上"),
                ],
                default="HIGH_SCHOOL",
                max_length=20,
                verbose_name="学历要求",
            ),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="experience",
            field=models.CharField(
                choices=[
                    ("FRESH", "应届毕业生"),
                    ("LESS_THAN_1", "1年以内"),
                    ("1_3", "1-3年"),
                    ("3_5", "3-5年"),
                    ("5_10", "5-10年"),
                    ("MORE_THAN_10", "10年以上"),
                ],
                default="FRESH",
                max_length=20,
                verbose_name="工作经验要求",
            ),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="job_desc",
            field=models.TextField(
                default="",
                help_text="详细描述岗位职责、工作内容",
                verbose_name="职位描述",
            ),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="job_require",
            field=models.TextField(
                default="",
                help_text="详细描述技能要求、资格条件等",
                verbose_name="任职要求",
            ),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="salary",
            field=models.CharField(
                default="面议",
                help_text="例如：10k-20k/月 或 150-300元/天",
                max_length=100,
                verbose_name="薪资范围",
            ),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="title",
            field=models.CharField(
                help_text="例如：【急聘】资深Python开发工程师",
                max_length=200,
                verbose_name="招聘标题",
            ),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="work_location",
            field=models.CharField(
                db_index=True,
                default="面议",
                help_text="例如：北京市海淀区中关村",
                max_length=200,
                verbose_name="工作地点",
            ),
        ),
        migrations.AddIndex(
            model_name="recruitment",
            index=models.Index(
                fields=["status", "deadline"], name="enterprise__status_e8fb9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recruitment",
            index=models.Index(
                fields=["is_urgent"], name="enterprise__is_urge_a46c54_idx"
            ),
        ),
    ]
