# Generated by Django 5.2.6 on 2025-12-13 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0003_alter_recruitment_deadline_jobapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitment",
            name="job",
            field=models.TextField(
                default="",
                help_text="岗位名称，如“软件工程师”",
                verbose_name="职位名称",
            ),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="deadline",
            field=models.DateField(
                default=datetime.date(2026, 1, 12),
                help_text="招聘信息有效期截止日期",
                verbose_name="截止日期",
            ),
        ),
    ]
