# Generated by Django 5.2.6 on 2025-12-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0004_recruitment_job_alter_recruitment_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitment",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "全职"),
                    ("PART_TIME", "兼职"),
                    ("实习", "INTERNSHIP"),
                ],
                default="全职",
                help_text="选择全职/兼职/实习",
                max_length=20,
                verbose_name="工作类型",
            ),
        ),
    ]
