# Generated by Django 5.2.6 on 2025-12-16 19:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0006_alter_recruitment_job_type"),
        ("resume", "0002_alter_resume_pdf_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobapplication",
            options={"verbose_name": "职位申请", "verbose_name_plural": "职位申请"},
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resume.resume",
            ),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="deadline",
            field=models.DateField(
                default=datetime.date(2026, 1, 15),
                help_text="招聘信息有效期截止日期",
                verbose_name="截止日期",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together={("recruitment", "applicant")},
        ),
    ]
