# Generated by Django 5.2.6 on 2025-12-30 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0008_alter_recruitment_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="applications/resumes/"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="resume_snapshot",
            field=models.JSONField(default=dict, verbose_name="简历快照"),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="deadline",
            field=models.DateField(
                default=datetime.date(2026, 1, 29),
                help_text="招聘信息有效期截止日期",
                verbose_name="截止日期",
            ),
        ),
    ]
