# Generated by Django 5.2.6 on 2025-12-31 17:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0009_jobapplication_pdf_file_and_more"),
        ("resume", "0002_alter_resume_pdf_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="pdf_file",
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="pdf_url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="PDF文件路径"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="resume.resume",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "待处理"),
                    ("VIEWED", "已查看"),
                    ("INTERVIEW", "待面试"),
                    ("REJECTED", "已拒绝"),
                    ("HIRED", "已录用"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="deadline",
            field=models.DateField(
                default=datetime.date(2026, 1, 30),
                help_text="招聘信息有效期截止日期",
                verbose_name="截止日期",
            ),
        ),
    ]
