# Generated by Django 5.2.6 on 2025-12-31 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0010_remove_jobapplication_pdf_file_and_more"),
        ("resume", "0002_alter_resume_pdf_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="pdf_url",
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="applications/resumes/"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resume.resume",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "待处理"),
                    ("VIEWED", "已查看"),
                    ("INTERVIEW", "待面试"),
                    ("REJECTED", "已拒绝"),
                    ("HIRED", "已录用"),
                ],
                max_length=20,
            ),
        ),
    ]
