# Generated by Django 5.2.6 on 2025-12-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0011_remove_jobapplication_pdf_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="applications/resumes/%Y/%m/%d/",
                verbose_name="PDF简历",
            ),
        ),
    ]
