# Generated by Django 5.2.6 on 2026-01-03 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0012_alter_jobapplication_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitment",
            name="deadline",
            field=models.DateField(
                default=datetime.date(2026, 2, 2),
                help_text="招聘信息有效期截止日期",
                verbose_name="截止日期",
            ),
        ),
    ]
