# Generated by Django 5.2.6 on 2026-01-03 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0013_alter_recruitment_deadline"),
        ("resume", "0002_alter_resume_pdf_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="申请用户的用户名",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="recruitment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enterprise.recruitment",
                verbose_name="招聘信息",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resume.resume",
                verbose_name="简历",
            ),
        ),
    ]
