# Generated by Django 5.2.6 on 2026-01-14 00:03

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0016_alter_recruitment_deadline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitment",
            name="deadline",
            field=models.DateField(
                default=datetime.date(2026, 2, 13),
                help_text="招聘信息有效期截止日期",
                verbose_name="截止日期",
            ),
        ),
        migrations.CreateModel(
            name="TalentPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume_snapshot",
                    models.JSONField(default=dict, verbose_name="简历快照"),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=500, verbose_name="标签"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "活跃"),
                            ("ARCHIVED", "已归档"),
                            ("BLACKLIST", "黑名单"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="人才状态",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="评分",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="talent_pool_entry",
                        to="enterprise.jobapplication",
                        verbose_name="关联的申请记录",
                    ),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talent_pool",
                        to="enterprise.enterprise",
                        verbose_name="所属企业",
                    ),
                ),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talent_pool_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="求职者",
                    ),
                ),
            ],
            options={
                "verbose_name": "人才库",
                "verbose_name_plural": "人才库",
                "ordering": ["-added_at"],
                "unique_together": {("enterprise", "job_seeker")},
            },
        ),
        migrations.CreateModel(
            name="TalentPoolTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="标签名称")),
                (
                    "color",
                    models.CharField(
                        default="#1890ff", max_length=7, verbose_name="标签颜色"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talent_tags",
                        to="enterprise.enterprise",
                        verbose_name="所属企业",
                    ),
                ),
            ],
            options={
                "verbose_name": "人才库标签",
                "verbose_name_plural": "人才库标签",
                "unique_together": {("enterprise", "name")},
            },
        ),
    ]
