# Generated by Django 5.2.6 on 2026-01-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0017_alter_recruitment_deadline_talentpool_talentpooltag"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentpool",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="talent_pool/resumes/%Y/%m/%d/",
                verbose_name="PDF简历",
            ),
        ),
    ]
