# Generated by Django 5.2.6 on 2026-01-18 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0020_alter_recruitment_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitment",
            name="deadline",
            field=models.DateField(
                default=datetime.date(2026, 2, 17),
                help_text="招聘信息有效期截止日期",
                verbose_name="截止日期",
            ),
        ),
    ]
