# Generated by Django 5.2.6 on 2026-01-24 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0023_alter_recruitment_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitment",
            name="job_category",
            field=models.CharField(
                choices=[
                    ("SOFTWARE", "软件开发"),
                    ("BACKEND", "后端开发"),
                    ("FRONTEND", "前端开发"),
                    ("MOBILE", "移动开发"),
                    ("TEST", "测试"),
                    ("DEVOPS", "运维"),
                    ("PRODUCT", "产品"),
                    ("DESIGN", "设计"),
                    ("MARKETING", "市场"),
                    ("SALES", "销售"),
                    ("HR", "人力资源"),
                    ("FINANCE", "财务"),
                    ("OTHER", "其他"),
                ],
                default="OTHER",
                help_text="选择职位所属类别",
                max_length=20,
                verbose_name="职位类别",
            ),
        ),
        migrations.AddField(
            model_name="recruitment",
            name="recruit_type",
            field=models.CharField(
                choices=[
                    ("CAMPUS", "校招"),
                    ("SOCIAL", "社招"),
                    ("INTERNSHIP", "实习"),
                ],
                default="SOCIAL",
                help_text="选择校招/社招/实习",
                max_length=20,
                verbose_name="招聘类型",
            ),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="deadline",
            field=models.DateField(
                default=datetime.date(2026, 2, 23),
                help_text="招聘信息有效期截止日期",
                verbose_name="截止日期",
            ),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "全职"),
                    ("PART_TIME", "兼职"),
                    ("INTERNSHIP", "实习"),
                ],
                default="FULL_TIME",
                help_text="选择全职/兼职/实习",
                max_length=20,
                verbose_name="工作类型",
            ),
        ),
    ]
