# Generated by Django 5.2.6 on 2026-01-26 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "enterprise",
            "0024_recruitment_job_category_recruitment_recruit_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="请填写企业官方网站链接",
                null=True,
                verbose_name="企业官网",
            ),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="deadline",
            field=models.DateField(
                default=datetime.date(2026, 2, 25),
                help_text="招聘信息有效期截止日期",
                verbose_name="截止日期",
            ),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="recruit_type",
            field=models.CharField(
                choices=[
                    ("CAMPUS", "校招"),
                    ("SOCIAL", "社招"),
                    ("INTERNSHIP", "实习"),
                ],
                default="CAMPUS",
                help_text="选择校招/社招/实习",
                max_length=20,
                verbose_name="招聘类型",
            ),
        ),
    ]
