# Generated by Django 5.2.6 on 2026-01-27 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0026_alter_recruitment_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="contact_phone",
            field=models.CharField(
                help_text="请填写有效的电话号码（支持手机号、固定电话、400/800等客服电话）",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\d\\-\\+\\s\\(\\)]{7,20}$", "请输入有效的电话号码"
                    )
                ],
                verbose_name="联系电话",
            ),
        ),
    ]
