# Generated by Django 5.2.6 on 2026-03-14 13:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0031_alter_recruitment_deadline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitment",
            name="deadline",
            field=models.DateField(
                default=datetime.date(2026, 4, 13),
                help_text="招聘信息有效期截止日期",
                verbose_name="截止日期",
            ),
        ),
        migrations.CreateModel(
            name="RecruitmentFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "recruitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="enterprise.recruitment",
                        verbose_name="收藏的职位",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_recruitments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="收藏用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "职位收藏",
                "verbose_name_plural": "职位收藏",
                "ordering": ["-created_at"],
                "unique_together": {("user", "recruitment")},
            },
        ),
    ]
