# Generated by Django 6.0.2 on 2026-03-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0032_alter_recruitment_deadline_recruitmentfavorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talentpool",
            name="status",
            field=models.CharField(
                choices=[
                    ("WRITTEN_TEST", "笔试"),
                    ("INTERVIEW", "面试"),
                    ("HIRED", "已录用"),
                    ("ELIMINATED", "已淘汰"),
                ],
                default="WRITTEN_TEST",
                max_length=20,
                verbose_name="人才状态",
            ),
        ),
    ]
