# Generated by Django 6.0.2 on 2026-03-19 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0034_alter_recruitment_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitment",
            name="deadline",
            field=models.DateField(
                default=datetime.date(2026, 4, 18),
                help_text="招聘信息有效期截止日期",
                verbose_name="截止日期",
            ),
        ),
    ]
