"""
Django settings for graduation project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-wdujae!ea8)=vffb4+4u^u45%l_q6&f#mdxnm0zf1m(1)i$)p2"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'notification': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'channels': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "colorfield",  # django-admin-interface依赖
    "admin_interface",  # Django Admin Interface主题
    "rest_framework", #DRF
    "corsheaders", #CORS
    "register.apps.RegisterConfig", #注册功能
    'rest_framework_simplejwt',  # JWT认证
    "user_info.apps.UserInfoConfig", #用户信息
    "resume.apps.ResumeConfig", #简历
    "article_publish.apps.ArticlePublishConfig", #文章发布
    "enterprise.apps.EnterpriseConfig", #企业模块
    "chat.apps.ChatConfig", #聊天模块
    "channels", #Django Channels
    "notification.apps.NotificationConfig", #通知模块
]

ASGI_APPLICATION = "graduation.asgi.application"

# 配置 Channels 后端（使用Redis）
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

AUTH_USER_MODEL = "register.User"

# Session配置
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_AGE = 1209600  # 2周（秒）
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware", #CORS
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# CORS配置
CORS_ALLOW_ALL_ORIGINS = True  # 开发环境允许所有源
CORS_ALLOW_CREDENTIALS = True  # 允许携带Cookie
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

ROOT_URLCONF = "graduation.urls"

# Django Admin 站点配置
ADMIN_SITE_TITLE = "大学生就业信息共享平台后台系统"
ADMIN_SITE_HEADER = "大学生就业信息共享平台后台系统"
ADMIN_INDEX_TITLE = "欢迎来到大学生就业信息共享平台后台系统"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "graduation.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",  # 使用MySQL引擎
        "NAME": "employment_platform",  # 数据库名称（需提前在MySQL中创建）
        "USER": "root",  # 你的MySQL用户名
        "PASSWORD": "123456",  # 你的MySQL密码
        "HOST": "localhost",  # 数据库主机，本地默认localhost
        "PORT": "3306",  # MySQL默认端口
        "OPTIONS": {
            "charset": "utf8mb4",  # 支持emoji等特殊字符
        }
    }
}

X_FRAME_OPTIONS = 'ALLOWALL'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = False

MEDIA_URL = '/media/'  # 访问媒体文件的URL前缀
MEDIA_ROOT = BASE_DIR / 'media'  # 本地保存路径（项目根目录/media）

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'graduation' / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 允许所有来源进行跨域请求（开发阶段使用，生产环境请配置具体域名）
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",#这是Vite默认的前端开发服务器地址
    "http://127.0.0.1:5173",
]

CORS_ALLOW_METHODS = [
    "GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"  # 允许必要的请求方法
]
CORS_ALLOW_CREDENTIALS = True # 允许携带Cookie
CORS_ALLOW_HEADERS = [
    "content-type", "authorization"  # 允许表单类型和令牌头
]

# Django REST Framework 配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ], 
}

# Simple JWT 配置
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),  # 访问令牌有效期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # 刷新令牌有效期
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'TOKEN_OBTAIN_SERIALIZER': 'register.serializers.CustomTokenObtainPairSerializer',
}

# Django Admin Interface 配置
X_FRAME_OPTIONS = 'SAMEORIGIN'

# 主题配置
ADMIN_TITLE = '大学生就业信息共享平台'
ADMIN_HEADER_COLOR = 'rgb(95, 133, 127)'  # 与平台主色调一致（绿色）
ADMIN_NAME = '就业平台管理后台'

# 模块配置
ADMIN_INTERFACE = {
    'name': '大学生就业信息共享平台',
    'header_color': 'rgb(95, 133, 127)',
    'title_color': '#FFFFFF',
    'env_name': 'Development',
    'language_selector': True,
    'show_apps_as_dropdown': True,
    'show_bookmarks': True,
    'show_history': True,
    'hide_app_index': False,
    'logo': {
        'visible': False,
    },
    'related_modal': True,
    'navigation_collapse': False,
    'navigation_expanded': False,
    'submit_buttons': 'right',
    'list_filter_dropdown': True,
    'list_filter_sticky': True,
    'search_autocomplete': False,
    'theme_toggle': True,
    'compact_tables': False,
    'form_submit_sticky': True,
    'form_pagination_sticky': True,
    'recent_actions_visible': True,
}