# Generated by Django 5.2.6 on 2025-10-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_enterprise",
            field=models.BooleanField(default=False, verbose_name="是否企业用户"),
        ),
    ]
