# Generated by Django 5.2.6 on 2026-01-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_user_is_enterprise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="用户昵称"
            ),
        ),
    ]
