# Generated by Django 5.2.6 on 2026-01-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_alter_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="地址"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(blank=True, null=True, verbose_name="年龄"),
        ),
        migrations.AlterField(
            model_name="user",
            name="current_status",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="当前状态"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="education_level",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="学历"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="graduation_school",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="毕业学校"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="graduation_year",
            field=models.IntegerField(blank=True, null=True, verbose_name="毕业年份"),
        ),
        migrations.AlterField(
            model_name="user",
            name="intended_city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="意向城市"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="intended_position",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="意向职位"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="intended_salary",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="意向薪资"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="major",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="专业"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="personal_profile",
            field=models.TextField(
                blank=True, max_length=600, null=True, verbose_name="个人简介"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="电话号码"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="性别"
            ),
        ),
    ]
