# Generated by Django 5.2.6 on 2026-01-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0004_alter_user_address_alter_user_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="用户头像"
            ),
        ),
    ]
