# Generated by Django 5.2.6 on 2026-01-16 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("resume_received", "收到简历"),
                            ("jobseeker_message", "收到求职者私信"),
                            ("system_notification", "系统通知"),
                            ("interview_invitation", "面试邀请"),
                            ("application_status_update", "招聘流程更新"),
                            ("company_chat", "企业发起聊天"),
                            ("report_feedback", "举报反馈"),
                            ("post_comment", "帖子评论"),
                            ("user_followed", "被关注"),
                            ("user_message", "用户私信"),
                            ("system_general", "系统通用通知"),
                        ],
                        max_length=50,
                        verbose_name="通知类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="通知标题")),
                ("message", models.TextField(verbose_name="通知内容")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="是否已读"),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="关联对象ID"
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="关联对象类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收者",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "ordering": ["-created_at"],
            },
        ),
    ]
