# Generated by Django 5.2.6 on 2026-01-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("resume_received", "收到简历"),
                    ("jobseeker_message", "收到求职者私信"),
                    ("system_notification", "系统通知"),
                    ("interview_invitation", "面试邀请"),
                    ("application_status_update", "招聘流程更新"),
                    ("company_chat", "企业发起聊天"),
                    ("report_feedback", "举报反馈"),
                    ("post_comment", "帖子评论"),
                    ("post_liked", "帖子被点赞"),
                    ("post_collected", "帖子被收藏"),
                    ("user_followed", "被关注"),
                    ("user_message", "用户私信"),
                    ("system_general", "系统通用通知"),
                ],
                max_length=50,
                verbose_name="通知类型",
            ),
        ),
    ]
