# Generated by Django 5.2.6 on 2025-09-29 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=50, verbose_name="姓名"),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "男"), ("F", "女")],
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "education",
                    models.CharField(blank=True, max_length=50, verbose_name="学历"),
                ),
                (
                    "internship_experience",
                    models.TextField(blank=True, verbose_name="实习经历"),
                ),
                (
                    "work_experience",
                    models.TextField(blank=True, verbose_name="工作经历"),
                ),
                (
                    "project_experience",
                    models.TextField(blank=True, verbose_name="项目经历"),
                ),
                (
                    "school_experience",
                    models.TextField(blank=True, verbose_name="校园经历"),
                ),
                (
                    "self_evaluation",
                    models.TextField(blank=True, verbose_name="自我评价"),
                ),
                ("scholarships", models.TextField(blank=True, verbose_name="奖学金")),
                (
                    "skills",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="技能标签"
                    ),
                ),
                (
                    "job_objective",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="求职意向"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("published", "已发布")],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "pdf_url",
                    models.URLField(blank=True, null=True, verbose_name="PDF地址"),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "简历",
                "verbose_name_plural": "简历",
                "ordering": ["-updated_at"],
            },
        ),
    ]
