# Generated by Django 5.2.6 on 2025-10-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="pdf_url",
            field=models.FileField(blank=True, null=True, upload_to="resumes/pdf/"),
        ),
    ]
