# Generated by Django 5.2.6 on 2026-03-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_alter_resume_pdf_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="major",
            field=models.CharField(blank=True, max_length=100, verbose_name="专业"),
        ),
        migrations.AddField(
            model_name="resume",
            name="school",
            field=models.CharField(blank=True, max_length=100, verbose_name="毕业院校"),
        ),
    ]
