# Generated by Django 6.0.2 on 2026-03-03 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("ENTERPRISE", "企业认证"),
                            ("INDIVIDUAL", "个人认证"),
                        ],
                        max_length=20,
                        verbose_name="认证类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待审核"),
                            ("APPROVED", "已通过"),
                            ("REJECTED", "已拒绝"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="真实姓名")),
                ("id_number", models.CharField(max_length=18, verbose_name="身份证号")),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                (
                    "business_license",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="verifications/business_licenses/",
                        verbose_name="营业执照",
                    ),
                ),
                (
                    "student_card",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="verifications/student_cards/",
                        verbose_name="学信网截图",
                    ),
                ),
                (
                    "other_files",
                    models.JSONField(
                        default=list,
                        help_text="存储其他证明文件的URL列表",
                        verbose_name="其他证明文件",
                    ),
                ),
                (
                    "reject_reason",
                    models.TextField(blank=True, null=True, verbose_name="拒绝原因"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "认证申请",
                "verbose_name_plural": "认证申请",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="user_info_v_user_id_db5ef1_idx"
                    ),
                    models.Index(
                        fields=["verification_type", "status"],
                        name="user_info_v_verific_e4d462_idx",
                    ),
                ],
            },
        ),
    ]
