# Generated by Django 5.2.6 on 2026-03-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_info", "0002_follow"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
