# Generated by Django 5.2.6 on 2026-03-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_info", "0004_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensitiveWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="敏感词"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "敏感词",
                "verbose_name_plural": "敏感词",
                "ordering": ["-created_at"],
            },
        ),
    ]
